modLoader="javafml"
loaderVersion="[31,)"
issueTrackerURL="https://github.com/TeamKun/Gullivern/issues"
license="MIT"

[[mods]]
modId="gulliver"
version="${file.jarVersion}"
displayName="Gullivern"
displayURL="https://github.com/TeamKun/Gullivern"
logoFile="logo.png"
credits="Kamesuta"
authors="Kamesuta"
description='''
A remake of some of the features from the Gulliver Mod.
'''
[[dependencies.gulliver]]
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[31,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.gulliver]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.4, 1.16.5]"
    ordering="NONE"
    side="BOTH"
