modLoader="javafml"
loaderVersion="[31,)"
issueTrackerURL="https://github.com/Kamesuta/Gulliver-1.15.2/issues"

[[mods]]
modId="gulliver"
version="${file.jarVersion}"
displayName="Gulliver-1.15.2"
displayURL="https://github.com/Kamesuta/Gulliver-1.15.2/"
logoFile="logo.png"
credits="Kamesuta"
authors="Kamesuta"
description='''
A remake of some of the features from the Gulliver Mod.
'''
[[dependencies.examplemod]]
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[31,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.examplemod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"
